---
dependency:
  name: galaxy
  options:
    role-file: molecule/requirements.yml
driver:
  name: hetznercloud
lint: yamllint .
platforms:
  - name: molecule-hub${INSTANCE_NAME_SUFFIX}
    server_type: cx11
    image: ubuntu-18.04
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: /usr/bin/python3
  env:
    LOCAL_MOUNT_PATH: /tmp/localmount
  log: true
  lint: ansible-lint
verifier:
  name: ansible
  lint: ansible-lint
