---
- name: Assert compatible Backend Version
  assert:
    that: ('latest' in portal_backend_version) or (portal_backend_version is version('4.0.0', '>='))
    fail_msg: This role version does only support Portal Backend versions newer than 4.0.0

- name: Setup required data volumes
  become: true
  import_tasks: data_volumes.yml

- name: Collect environment variables for the main application server
  set_fact:
    base_server_environment_variables:
      DOMAIN: "{{ admin_configuration.domain }}"
      DJANGO_SECRET_KEY: "{{ admin_configuration.secret_key | mandatory }}"
      FROM_EMAIL: "{{ admin_configuration.from_email | default('admin@' + admin_configuration.domain, true) }}"
      RAVEN_DSN: "{{ admin_configuration.sentry_dsn | default('') }}"
      GOOGLE_ANALYTICS_TRACKING_ID: "{{ admin_configuration.google_analytics_id | default('') }}"
      EMAIL_HOST: "{{ mail_configuration.smtp.host }}"
      EMAIL_PORT: "{{ mail_configuration.smtp.port }}"
      EMAIL_USER: "{{ mail_configuration.smtp.user }}"
      EMAIL_PASSWORD: "{{ mail_configuration.smtp.password }}"
      EMAIL_USE_TLS: "{{ mail_configuration.smtp.use_tls | ternary('True', 'False') | string }}"
      EMAIL_USE_SSL: "{{ mail_configuration.smtp.use_ssl | ternary('True', 'False') | string }}"
      CUSTOMIZATION_SERVICE_API_URL: "{{ admin_configuration.protocol }}://{{ customization_configuration.hostname }}/api"
      CLOUD_RENDERING_CLIENT_APPLICATION_CLIENT_ID: "{{ desktop_client_configuration.remote_oauth2_client_id }}"
      GOOGLE_TAG_MANAGER_ID: "{{ admin_configuration.google_tag_manager_id | default('') }}"

- name: Start Django Application Server
  vars:
    traefik_labels:
      traefik.enable: "true"
      traefik.http.routers.web.rule: HostRegexp(`admin.{subdomain:[\w-_]+}.{{ admin_configuration.domain }}`,`api.{{ admin_configuration.domain }}`,`admin.{{ admin_configuration.domain }}`)
      traefik.http.routers.web.tls: "{{ traefik.enable_tls | ternary('true', 'false') }}"
      traefik.http.routers.web.tls.certresolver: "{{ traefik.certificate_resolver }}"
    base_volumes:
      - "{{ volume_names.media }}:/media"
  docker_container:
    name: "{{ container_names.backend }}"
    image: "{{ image_versions.portal_backend }}"
    # pull image if version is latest
    pull: "{{ portal_backend_version_is_latest }}"
    restart_policy: unless-stopped
    volumes: "{{ base_volumes + admin_configuration.extra_volumes }}"
    env: "{{ base_server_environment_variables | combine(admin_configuration.extra_environment_variables) }}"
    labels: "{{ traefik_labels | combine(admin_configuration.extra_labels) }}"
    comparisons:
      # correctly recreate container when any environment variable or labels is changed or added / removed
      env: strict
      labels: allow_more_present
    networks_cli_compatible: true
    network_mode: default
    networks:
      - name: "{{ network_names.main }}"
        aliases:
          - web

- name: Run Database Migrations
  command: "docker exec {{ container_names.backend }} python manage.py migrate"
  register: migration_result
  changed_when: '"Applying" in migration_result.stdout'
  when: admin_configuration.setup_database
  tags:
    - setup_tasks
    - requires_database

- name: Collect static files for Control Panel
  # yamllint disable rule:line-length
  command: "docker exec {{ container_names.backend }} python manage.py collectstatic -v 0 -c --no-input"
  register: collect_static_result
  # yamllint enable rule:line-length
  when: admin_configuration.setup_control_panel
  # TODO: technically, this is not correct, it should only be changed
  # if no files are collected but django doesn't tell us ...
  changed_when: false
  tags:
    - setup_tasks

# FIXME: This should be handled in the Django application setup automatically
- name: Change default Site name and domain
  shell: "{{ lookup('template', 'run_in_django_shell.sh.j2') }}" # noqa 305
  vars:
    python_script_name: change_site_name_and_domain
    site_name: "admin.{{ admin_configuration.domain[:49] }}"
    domain: "admin.{{ admin_configuration.domain }}"
  register: site_update_output
  changed_when: site_update_output.stdout | trim | bool
  tags:
    - setup_tasks
    - requires_database
