---
- name: Create Hub database data volume
  docker_volume:
    name: "{{ volume_names.database }}"

- name: Start Database
  docker_container:
    name: "{{ container_names.database }}"
    image: "{{ image_versions.database }}"
    restart_policy: unless-stopped
    env:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - "{{ volume_names.database }}:/var/lib/postgresql/data"
    networks_cli_compatible: true
    network_mode: default
    networks:
      - name: "{{ network_names.main }}"
        aliases:
          - db

- name: Create Hub message queue data volume
  docker_volume:
    name: "{{ volume_names.message_queue }}"

- name: Start Message Queue
  docker_container:
    name: "{{ container_names.message_queue }}"
    image: "{{ image_versions.message_queue }}"
    volumes:
      - "{{ volume_names.message_queue }}:/data"
    restart_policy: unless-stopped
    networks_cli_compatible: true
    network_mode: default
    networks:
      - name: "{{ network_names.main }}"
        aliases:
          - redis
