---
- name: Determine whether volume creation mode
  block:
    - name: Setup variables
      set_fact:
        use_cifs_mount: no
        use_bind_mount: no
        use_device_mount: no
    - name: Determine whether volume should be created via Samba / CIFS
      set_fact:
        use_cifs_mount: yes
      when:
        - media_volume_mount.cifs is defined
        - media_volume_mount.cifs.url is defined
        - media_volume_mount.cifs.url | default('', true) | trim | length > 0

    - name: Determine whether volume should be created via bind mount
      set_fact:
        use_bind_mount: yes
      when:
        - media_volume_mount.local is defined
        - media_volume_mount.local.path is defined
        - media_volume_mount.local.path | default('', true) | trim | length > 0

    - name: Determine whether volume should be created via a device mount
      set_fact:
        use_device_mount: yes
      when:
        - media_volume_mount.device is defined
        - media_volume_mount.device.path is defined
        - media_volume_mount.device.path | default('', true) | trim | length > 0

    - name: Assert Variables
      assert:
        that:
          # after selecting all (truthy) mount option flags, we should only have one left
          - mount_option_flags | select() | list | length <= 1
        fail_msg: "Cannot specify multiple options for configuring the media volume!"
        quiet: yes
      vars:
        mount_option_flags:
          - "{{ use_cifs_mount | default(false, true) }}"
          - "{{ use_bind_mount | default(false, true) }}"
          - "{{ use_device_mount | default(false, true) }}"

- name: Create Hub's media data volume (without any mount)
  docker_volume:
    name: "{{ volume_names.media }}"
  when:
    - not use_cifs_mount
    - not use_bind_mount
    - not use_device_mount

- name: Define Volume Mount path
  set_fact:
    media_storage_path: /mnt/hub-media-storage
  when: use_cifs_mount or use_bind_mount or use_device_mount

- name: Bind-Mount Media Volume to existing directory
  import_tasks: media_volume_bind.yml
  when:
    - not use_cifs_mount
    - use_bind_mount
    - not use_device_mount

- name: Mount Media Volume via CIFS
  import_tasks: media_volume_cifs.yml
  when:
    - use_cifs_mount
    - not use_bind_mount
    - not use_device_mount

- name: Mount Media Volume via Device Mount
  import_tasks: media_volume_device.yml
  when:
    - not use_cifs_mount
    - not use_bind_mount
    - use_device_mount

- name: Create Hub's media (docker) volume at specified mount path
  docker_volume:
    name: "{{ volume_names.media }}"
    driver_options:
      device: "{{ media_storage_path }}"
      type: local
      o: bind
  when: use_cifs_mount or use_bind_mount or use_device_mount
