---
- name: Allow Desktop Client to communicate with Backend
  shell: "{{ lookup('template', 'run_in_django_shell.sh.j2') }}" # noqa 305
  vars:
    python_script_name: get_oauth_client_credentials
    authorization_type: GRANT_DEVICE_AUTH
    client_name: Innoactive Portal Desktop Client
    client_id: "{{ desktop_client_configuration.oauth2_client_id }}"
    client_secret: "{{ desktop_client_configuration.oauth2_client_secret }}"
  register: portal_desktop_client_oauth_client_output
  changed_when: portal_desktop_client_oauth_client_output.stdout | from_json | json_query('changed')
  tags:
    - requires_database

- name: Remote Desktop Client CloudXR credentials
  shell: "{{ lookup('template', 'run_in_django_shell.sh.j2') }}" # noqa 305
  vars:
    python_script_name: get_oauth_client_credentials
    authorization_type: GRANT_DEVICE_AUTH
    client_name: Innoactive Portal Desktop Client CloudXR Remote Client
    client_id: "{{ desktop_client_configuration.remote_oauth2_client_id }}"
    client_secret: "{{ desktop_client_configuration.remote_oauth2_client_secret }}"
  register: portal_desktop_client_remote_oauth_client_output
  changed_when: portal_desktop_client_remote_oauth_client_output.stdout | from_json | json_query('changed')
  tags:
    - requires_database

- name: Identify Client Id for Desktop Client
  set_fact:
    desktop_client_configuration:
      oauth2_client_id: "{{ portal_desktop_client_oauth_client_output.stdout | from_json | json_query('client_id') }}"
      oauth2_client_secret: "{{ portal_desktop_client_oauth_client_output.stdout | from_json | json_query('client_secret') }}"
      remote_oauth2_client_id: "{{ portal_desktop_client_remote_oauth_client_output.stdout | from_json | json_query('client_id') }}"
      remote_oauth2_client_secret: "{{ portal_desktop_client_remote_oauth_client_output.stdout | from_json | json_query('client_secret') }}"

- name: Validate client credentials
  assert:
    that:
      - desktop_client_configuration.oauth2_client_id | default('', true) | length > 0
      - desktop_client_configuration.oauth2_client_secret | default('', true) | length > 0
      - desktop_client_configuration.remote_oauth2_client_id | default('', true) | length > 0
      - desktop_client_configuration.remote_oauth2_client_secret | default('', true) | length > 0
