---
- name: Allow Launcher to communicate with Hub Instance
  shell: "{{ lookup('template', 'run_in_django_shell.sh.j2') }}" # noqa 305
  vars:
    python_script_name: get_oauth_client_credentials
    authorization_type: GRANT_DEVICE_AUTH
    client_name: Innoactive Hub Launcher
    client_id: "{{ launcher_configuration.oauth2_client_id }}"
    client_secret: "{{ launcher_configuration.oauth2_client_secret }}"
    redirect_uris:
      - "http://127.0.0.1:51236/"
      - "http://127.0.0.1:51237/"
      - "http://localhost:51236/"
      - "http://localhost:51237/"
  register: launcher_oauth_client_output
  changed_when: launcher_oauth_client_output.stdout | from_json | json_query('changed')
  tags:
    - requires_database

- name: Identify Client Id for Customization Service
  set_fact:
    launcher_oauth2_client_id: "{{ launcher_oauth_client_output.stdout | from_json | json_query('client_id') }}"
    launcher_oauth2_client_secret: "{{ launcher_oauth_client_output.stdout | from_json | json_query('client_secret') }}"

- name: Validate client credentials
  assert:
    that:
      - launcher_oauth2_client_id | default('', true) | length > 0
      - launcher_oauth2_client_secret | default('', true) | length > 0