---
- name: Upload Fluentd Server certificates
  copy:
    src: "{{ item }}"
    dest: "{{ telemetry_certificate_path }}/"
  loop:
    - "{{ telemetry.tls_privatekey }}"
    - "{{ telemetry.tls_certificate }}"
    - "{{ telemetry.tls_ca_certificate }}"

- name: Create persistent Volume for FluentD logs
  docker_volume:
    name: "{{ volume_names.telemetry_logs }}"

- name: Start Fluentd Service
  docker_container:
    name: "{{ container_names.telemetry }}"
    image: "{{ image_versions.fluentd }}"
    # pull image if version is latest
    pull: "{{ (image_versions.fluentd | default(':', True)).split(':')[1] == 'latest' }}"
    restart_policy: unless-stopped
    volumes:
      - "{{ telemetry_certificate_path }}:/fluentd/etc/ssl:ro"
      - "{{ volume_names.telemetry_logs }}:/fluentd/log"
    exposed_ports:
      - "24224"
      - "24224/udp"
    published_ports:
      - "24284:24284"
      - "24284:24284/udp"
      - "24443:24443"
    env:
      FLUENTD_HOSTNAME: "{{ fluentd_configuration.hostname }}"
      FLUENTD_SHARED_KEY: "{{ telemetry.shared_key }}"
      FLUENTD_TLS_PRIVATE_KEY_PASSPHRASE: "{{ telemetry.tls_privatekey_passphrase }}"
      FLUENTD_SALT: "{{ telemetry.salt }}"
    networks_cli_compatible: yes
    networks:
      - name: "{{ network_names.main }}"
        aliases:
          - fluentd
