---
- name: Get Client Credentials for VR Standalone Client
  block:
    - name: Create / Determine existing client credentials in Application
      shell: "{{ lookup('template', 'run_in_django_shell.sh.j2') }}" # noqa 305
      vars:
        python_script_name: get_oauth_client_credentials
        authorization_type: GRANT_DEVICE_AUTH
        client_name: VR Standalone Client
        client_id: "{{ vr_standalone_client.oauth2_client_id }}"
        client_secret: "{{ vr_standalone_client.oauth2_client_secret }}"
        redirect_uris: 
          "http://127.0.0.1:51236/"
      register: vr_standalone_oauth2_client_output
      changed_when: vr_standalone_oauth2_client_output.stdout | from_json | json_query('changed')
      # ansible lint has an issue where it cannot bypass rules (like 305) within blocks
      # see https://github.com/ansible/ansible-lint/issues/484, so we need to explicitly skip
      tags:
        - skip_ansible_lint
        - requires_database

    - name: Identify Client Id for VR Standalone Client
      set_fact:
        vr_standalone_client:
          oauth2_client_id: "{{ vr_standalone_oauth2_client_output.stdout | from_json | json_query('client_id') }}"
          oauth2_client_secret: "{{ vr_standalone_oauth2_client_output.stdout | from_json | json_query('client_secret') }}"

- name: Validate client credentials
  assert:
    that:
      - vr_standalone_client.oauth2_client_id | default('', true) | length > 0
      - vr_standalone_client.oauth2_client_secret | default('', true) | length > 0
