---
dependency:
  name: galaxy
  options:
    role-file: molecule/with_cifs/requirements.yml
driver:
  name: hetznercloud
lint:
  name: yamllint
platforms:
  - name: molecule-hub${INSTANCE_NAME_SUFFIX}-cifs
    server_type: cx11
    image: ubuntu-18.04

scenario:
  converge_sequence:
    - converge
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: /usr/bin/python3
  log: true
  env:
    CIFS_USERNAME: cifsuser
    CIFS_PASSWORD: cifsaccess
    CIFS_SHARENAME: testshare
  playbooks:
    create: ../saas/create.yml
    prepare: prepare.yml
    converge: playbook.yml
    destroy: ../saas/destroy.yml
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  directory: ./tests/
  additional_files_or_dirs:
    - ../default/tests/*
  env:
    # yamllint disable rule:line-length
    # get rid of the DeprecationWarning messages of third-party libs,
    # see https://docs.pytest.org/en/latest/warnings.html#deprecationwarning-and-pendingdeprecationwarning
    # yamllint enable rule:line-length
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  lint:
    name: flake8
