---
- name: Converge
  hosts: all
  vars:
    # main configuration parameters
    registry_username: "{{ lookup('env','DOCKER_REGISTRY_USERNAME') }}"
    registry_password: "{{ lookup('env','DOCKER_REGISTRY_PASSWORD') }}"
    setup_database: true
    setup_control_panel: false
    letsencrypt: false
    secret_key: not-secret-at-all-but-okay-for-tests
    admin_hostname: admin.portal.localhost
    portal_hostname: portal.localhost
    customization_hostname: customization.portal.localhost
    session_management_hostname: session-management.portal.localhost
    admin_email: admin@innoactive.de
    admin_password: sup3rs3cur3pa55w0rdf0rt3st1ng
    extra_volumes:
      - "test:/test"
    # change the default prefix to easily identify test containers / services
    service_prefix: molecule_test_hub
    # since the default case (using docker) mounts files from the local machine, we need to override the path
    signalling_proxy_configuration_path: "{{ playbook_dir }}/../../files/signalling-proxy/"
  roles:
    - role: geerlingguy.docker
      vars:
        # since we'll already have docker in our test environment, we skip the
        # respective role
        docker_service_state: stopped
        docker_service_enabled: false
        docker_install_compose: false
    - role: ../../../.
