---
- name: Converge
  hosts: all
  vars:
    # main configuration parameters
    registry_username: "{{ lookup('env','DOCKER_REGISTRY_USERNAME') }}"
    registry_password: "{{ lookup('env','DOCKER_REGISTRY_PASSWORD') }}"
    setup_database: true
    setup_wmc: false
    letsencrypt: false
    secret_key: not-secret-at-all-but-okay-for-tests
    admin_hostname: admin.portal.localhost
    portal_hostname: portal.localhost
    customization_hostname: customization.portal.localhost
    admin_email: admin@innoactive.de
    admin_password: sup3rs3cur3pa55w0rdf0rt3st1ng
    # change the default prefix to easily identify test containers / services
    hub_service_prefix: molecule_test_hub
    jwt_local_key_path: "{{ (playbook_dir + '/../sample_keys/jwt') | realpath }}"
    # Because docker in docker uses the host system instead of the actual remote
    jwt_key_path: "{{ jwt_local_key_path }}"
  roles:
    - role: geerlingguy.docker
      vars:
        # since we'll already have docker in our test environment, we skip the
        # respective role
        docker_service_state: stopped
        docker_service_enabled: false
        docker_install_compose: false
      become: true
    - role: ../../../.
