---
dependency:
  name: galaxy
  options:
    role-file: molecule/requirements.yml
driver:
  name: docker
lint: yamllint .
platforms:
  - name: molecule-docker${INSTANCE_NAME_SUFFIX}
    image: debian:stretch-slim
    privileged: true
    volumes:
      # mount the docker.sock so that we can start other docker containers
      - /var/run/docker.sock:/var/run/docker.sock:rw
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: converge.yml
    cleanup: cleanup.yml
    prepare: prepare.yml
  env:
    ANSIBLE_ROLES_PATH: $HOME/.ansible/roles
    DOCKER_REGISTRY_USERNAME: ${DOCKER_REGISTRY_USERNAME}
    DOCKER_REGISTRY_PASSWORD: ${DOCKER_REGISTRY_PASSWORD}
  lint: ansible-lint
verifier:
  name: ansible
  lint: ansible-lint
