---
dependency:
  name: galaxy
  options:
    role-file: molecule/requirements.yml
driver:
  name: docker
lint: |
    yamllint .
platforms:
  - name: molecule-docker
    image: debian:stretch-slim
    privileged: true
    volumes:
      # mount the docker.sock so that we can start other docker containers
      - /var/run/docker.sock:/var/run/docker.sock:rw
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: converge.yml
    prepare: prepare.yml
    cleanup: cleanup.yml
  env:
    ANSIBLE_ROLES_PATH: $HOME/.ansible/roles
    DOCKER_REGISTRY_USERNAME: ${DOCKER_REGISTRY_USERNAME}
    DOCKER_REGISTRY_PASSWORD: ${DOCKER_REGISTRY_PASSWORD}
  lint: |
    ansible-lint
verifier:
  name: testinfra
  directory: ./tests/
  env:
    # yamllint disable rule:line-length
    # get rid of the DeprecationWarning messages of third-party libs,
    # see https://docs.pytest.org/en/latest/warnings.html#deprecationwarning-and-pendingdeprecationwarning
    # yamllint enable rule:line-length
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  lint: |
    flake8
  options:
    # show which tests where executed in test output
    v: 1
