---
- name: Prepare
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.docker
      vars:
        # since we'll already have docker in our test environment, we only install dependencies but not the service itself
        docker_service_state: stopped
        docker_service_enabled: false
        docker_install_compose: false
    # Install Pip
    - role: geerlingguy.pip
      become: true
      vars:
        pip_package: python3-pip
        pip_install_packages:
          - name: docker
      tags:
        - prerequisites
        - pip
