name: CI

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Commit Linter
      uses: wagoid/commitlint-github-action@v1.3.1
      with:
        firstParent: false
